api/urls.py
# from api.views import BookReviewDetailAPIView, BookReviewsAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = 'api'

router = DefaultRouter()
router.register("reviews", BookReviewsViewSet, basename='review')
urlpatterns = router.urls

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from .views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name='landing_page'),
    path("home/", home_page, name='home_page'),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),

    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = "users"
urlpatterns = [
    path("signup", SignUpView.as_view(), name='signup'),
    path("login", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile/edit/", ProfileUpdateView.as_view(), name='profile-edit')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.png")

users/forms.py
from django import forms

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        # parent class ni save metodi chaqiriladi
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserCreateForm, UserUpdateForm


# Create your views here.
class SignUpView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, "users/signup.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            # forms.py ichida save() funksiyasi bor
            create_form.save()

            # create user account
            return redirect('users:login')
        else:
            context = {
                "form": create_form
            }

            return render(request, "users/signup.html", context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, "users/login.html", {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            messages.success(request, "You have successfully logged in.")

            return redirect('books:list')
        else:
            return render(request, "users/login.html", {"login_form": login_form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):

        # WE CAN DELETE THE FOLLOWING LINES OF CODE BECAUSE LoginRequiredMixin itself does it instead.
        # IF A USER IS NOT LOGGED IN AND WANTS TO OPEN PROFILE PAGE, IT REDIRECTS TO LOGIN PAGE
        # if not request.user.is_authenticated:
        #     return redirect("users:login")

        return render(request, "users/profile.html", {'users': request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "users/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile.")

            return redirect("users:profile")

        return render(request, "users/profile_edit.html", {"form": user_update_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block content %}
  <h1>Login</h1>
  <div class="row">
    <div class="col-4">
      <form method="post">
        {% csrf_token %}
        {{ login_form | crispy }}
        <button type="submit" class="btn btn-primary" >Log in</button> <span class="ms-4">Not a member? Then, <a href="{% url 'users:signup' %}" class="btn btn-outline-success">Sign Up</a></span>
      </form>
    </div>
  </div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}Profile Page{% endblock %}

{% block content %}
    <div class=" image d-flex flex-column justify-content-center align-items-center">
        <button class="btn btn-outline-dark">
        <img class="profile-pic" alt="Profile picture" src="{{ user.profile_picture.url }}">
        </button>
        <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
        <span class="idd">@{{ user.username }}</span>
        <span class="idd">{{ user.email }}</span>
        <div class=" d-flex mt-2">
            <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">Edit Profile</a>
        </div>
        <div class="px-2 rounded mt-4 date">
            <span class="join">Joined: {{ user.date_joined|date:"M d, Y" }}</span>
        </div>
    </div>

{% endblock %}

users/templates/users/profile_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update Profile Page{% endblock %}

{% block content %}
  <h2>Edit Profile </h2>
  <div class="row">
    <div class="col-4">
      <form method="post" enctype="multipart/form-data">
        {%  csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="ms-3 btn btn-outline-success" >Save Changes</button>
      </form>
    </div>
  </div>

{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}SignUp Page{% endblock %}

{% block content %}

    <h1>Sign Up</h1>
    <div class="row">
        <div class="col-4">
            <form method='post' action="{% url 'users:signup' %}">
                {% csrf_token %}

                {{ form | crispy }}

                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}